spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=piacell-invoice-insight-secret-key-minimum-256-bits-long
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173