spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


app.jwt.secret=change-this-to-a-random-256-bit-secret-before-production-use
app.jwt.expiration-ms=3600000

app.cors.allowed-origins=http://localhost:5173,http://localhost:5174