-- Introduces the payments table: one invoice can have multiple payment attempts
-- (e.g. an UNPAID try followed by a later PAID one), so this is a proper
-- one-to-many child of invoices rather than columns bolted onto Invoice.
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    payment_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL,
    payment_channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reference_number VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
